// src/components/About.tsx
export function About() {
  return (
    <div>
      <p>
        Hi! My name is Davide and I love building things for the web. Whether
        it's a landing page, a microservice, or a whole system, I always enjoy
        writing code and solve some problems.
      </p>
      <p>
        I started coding at High School, when I was 16 and since then, my
        passion for coding and Computer Science in general has kept growing.
        That is why I decided to move to Bologna and study Computer Science at
        the University of Bologna, where I graduated in December 2016. I then
        decided to move London to start my carrer as a web developer. I have
        graduated from the University of Bologna with a Bachelors of Computer
        Science, in 2016 and after that I decided to move to London to start my
        career as a developer.
      </p>
      <p>
        A few years forward, and I have had the opportunity to work with and
        meet a lot of great talented people, from across the whole world. During
        this 5 years I have the chance to work across the full stack of
        development, from Database and API design & implemntation, to building
        UI interfaces with React. bla bla bla .....
      </p>
      <p>
        Currently, I am a Senior Frontend Engineer, and Tech Lead of the
        Bookable Squad @ Culture Trip. As a Teach Lead I always have to make
        sure that my team has all they need to carry on with their day to day
        job. If you are looking for a holiday, or if you just interested about
        what me and my amazing team do, please heade over to our Places To Stay,
        Experiences or TRIPS page and take a look.
      </p>
    </div>
  );
}

// src/lib/components/home/About.svelte
<section class="h-screen flex flex-col jsutify-center">
  <h1 class="text-accent font-bold">About Me</h1>
  <div class="flex items-start">
    <div class="flex flex-col w-1/2 mt-8">
      <p>
        Hi! My name is Davide and I love building things for the web. Whether
        it's a landing page, a microservice, or a whole system, I always enjoy
        writing some code and solve some problems.
        <br />
        <br />
        I started coding at High School, when I was 16 and since then, my passion
        for coding and Computer Science in general has kept growing. That is why
        I decided to move to Bologna and study Computer Science at the University
        of Bologna, where I graduated in December 2016. I then decided to move London
        to start my carrer as a web developer. I have graduated from the University
        of Bologna with a Bachelors of Computer Science, in 2016 and after that I
        decided to move to London to start my career as a developer.

        <br />
        <br />
        A few years forward, and I have had the opportunity to work with and meet
        a lot of great talented people, from across the whole world. During this
        5 years I have the chance to work across the full stack of development, from
        Database and API design & implemntation, to building UI interfaces with React.
        bla bla bla .....

        <br />
        <br />
        Currently, I am a Senior Frontend Engineer, and Tech Lead of the Bookable
        Squad @ Culture Trip. As a Teach Lead I always have to make sure that my
        team has all they need to carry on with their day to day job. If you are
        looking for a holiday, or if you just interested about what me and my amazing
        team do, please heade over to our
        <a href="https://www.culturetrip.com/places-to-stay/">Places To Stay</a
        >,
        <a href="https://www.culturetrip.com/experiences/">Experiences</a> or
        <a href="https://www.culturetrip.com/trips/">TRIPS</a> page and take a look.
      </p>
    </div>
    <div class="w-1/2 flex justify-center bg-primary">
      <img src="/img/boy.png" alt="illustration of myself" loading="lazy" />
    </div>
  </div>
</section>
